# 넘파이(Numpy)

# 1. 배열 생성

uv add numpy

In [18]:
# # import numpy as np
# np = numpy
# print(np)

## 1) 1차원 배열 생성

In [7]:
data = np.array([1,2,3,4,5])
print(data)
print(type(data))
data

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

## 2) 차원별 배열 생성

In [11]:
#2차원 
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#변수의 속성
print(arr2.ndim) #차원의 수
print(arr2.shape) #배열의 크기 (5,) 은 튜플이고 1차원

2
(2, 3)


In [16]:
#3차원 

arr3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ])

In [17]:
print(arr3.ndim) #차원의 수
print(arr3.shape) #배열의 크기 (5,) 은 튜플이고 1차원

3
(2, 2, 3)


## 3) 패턴이 있는 배열 생성

In [39]:
#모든 원소가 0인 배열 
arr1 = np.zeros((3, 3))
print(arr1)
#모든 원소가 1인 배열 
arr2 = np.ones((3, 3))
print(arr2)
#모든 원소가 ?인 배열 
arr3 = np.full((3, 3)), fill_vaue =99
print(arr3)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1642839949.py, line 8)

In [20]:
#난수 생성 
arr_random = np.random.random((2,3))
print(arr_random)

[[0.83194078 0.38048452 0.6810465 ]
 [0.440405   0.92538107 0.3767734 ]]


In [26]:
#정수 생성 
arr_random_int = np.random.randint(0,10,3)
print(arr_random_int)


[6 2 9]


In [ ]:
# np.arange(start, end, x) start부터 end-1까지 x 간격으로 배열 생성
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)

# 2. 배열 속성

In [40]:
import numpy as np
data1 = np.array([1,2,3,4,5])

data2 = np.array([[1,2,3],
                  [4,5,6]])
data3 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(type(data1))
print(type(data2))
print(type(data3))


print(data3.shape)
print(data3.size)
print(data3.ndim)
print(data3.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2, 3, 2)
12
3
int64


In [ ]:
#. dtype: 배열 안의 요소 타입 
#. ndim : 차원의 수 
#. shape 

In [ ]:
data1 = np.array([1,2,3,4,5])

# 3. 배열 변환

In [28]:
data = np.arange(0, 15)
print(data) 
data2 = data.reshape(5,3)
print(data2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [30]:
#행열 전환 
data3 = data2.transpose()
print(data2.shape)
print(data3)
print(data3.shape)

(5, 3)
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
(3, 5)


# 4. 연산

In [43]:
# 사칙연산
data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[10,20,30],[40,50,60]])

print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [44]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=2))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[12 15 18]
 [39 42 45]]
[[ 6 15 24]
 [33 42 51]]


# 5. 통계

In [ ]:
data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[10,20,30],[40,50,60]])

# sum, mean, var, std


In [50]:
print(data1.sum())
print(np.sum(data1))
print(np.sum(data1, axis=0))
print("="*50)
print(data1.mean())
print(np.mean(data1))
print(np.mean(data1, axis=0))
print("="*50)
print(data1.var())
print(np.var(data1))
print(np.var(data1, axis=0))
print("="*50)
print(data1.std())
print(np.std(data1))
print(np.std(data1, axis=0))

21
21
[5 7 9]
3.5
3.5
[2.5 3.5 4.5]
2.9166666666666665
2.9166666666666665
[2.25 2.25 2.25]
1.707825127659933
1.707825127659933
[1.5 1.5 1.5]


# 6. 실습